account/urls.py
#! /usr/bin/env python
# -*- coding:utf-8 -*-
from django.conf.urls import url
from django.contrib.auth.views import login
from django.contrib.auth.views import logout
from django.contrib.auth.views import logout_then_login
from django.contrib.auth.views import password_change
from django.contrib.auth.views import password_change_done
from django.contrib.auth.views import password_reset
from django.contrib.auth.views import password_reset_done
from django.contrib.auth.views import password_reset_confirm
from django.contrib.auth.views import password_reset_complete
from . import views

urlpatterns = [
    # url(r'^login/$', views.user_login, name='login'),
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^logout-then-login/$', logout_then_login, name='logout_then_login'),
    url(r'^logout-then-login/$', password_change, name='password_change'),
    url(r'^logout-then-login/$', password_change_done, name='password_change_done'),
    url(r'^password-change/$', password_change, name='password_change'),
    url(r'^password-change/done/$', password_change_done, name='password_change_done'),
    url(r'^password-reset/$', password_reset, name='password_reset'),
    url(r'^password-reset/done/$', password_reset_done, name='password_reset_done'),
    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', password_reset_confirm,
        name='password_reset_confirm'),
    url(r'^password-reset/complete/$', password_reset_complete, name='password_reset_complete'),
    url(r'^register/$',views.register, name='register'),
    url(r'^edit/$', views.edit, name='edit'),
]

bus/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include("account.urls")),
    url(r'^car/', include("car.urls",namespace="car")),
    url(r'^$', RedirectView.as_view(url='/account/login/'),),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = "车辆管理系统后台"

car/urls.py
#! /usr/bin/env python
# -*- coding:utf-8 -*-

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^car_index/$',views.test),
    url(r'^car_index/$', views.CarView.as_view(), name='car_index'),
    # url(r'^car_create/$', views.car_create, name='car_create'),
    url(r'^car_create_ajax/$', views.car_create_ajax, name='car_create_ajax'),
    url(r'^car_detail_ajax/$', views.car_detail_ajax, name='car_detail_ajax'),
    url(r'^get_car_info_ajax/$', views.get_car_info_ajax, name='get_car_info_ajax'),
    url(r'^car_search/$', views.CarSearchView.as_view(), name='car_search'),
    url(r'^static_car/$', views.static_car, name='static_car'),
    url(r'^car_by_year/$', views.car_by_year, name='car_by_year'),
    url(r'^car_by_month/$', views.car_by_month, name='car_by_month'),
    url(r'^car_by_day/$', views.car_by_day, name='car_by_day'),
    url(r'^car_by_year_detail/(?P<year>\d{4})/$', views.car_by_year_detail, name='car_by_year_detail'),
    url(r'^car_by_month_detail/(?P<year>\d{4})/(?P<month>\d{1,})/$', views.car_by_month_detail, name='car_by_month_detail'),
    url(r'^car_by_day_detail/(?P<year>\d{4})/(?P<month>\d{1,})/(?P<day>\d{1,})/$', views.car_by_day_detail, name='car_by_day_detail'),
    url(r'^static_car_month/(?P<year>\d{4})/(?P<month>\d{1,})/$', views.static_car_month, name='static_car_month'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,})/(?P<day>\d{1,})/(?P<name>[-\w]+)/$', views.car_detail, name="car_detail"),
    url(r'^driver/$', views.driver, name='driver'),
    url(r'^saler/$', views.saler, name='saler'),
    url(r'^driver_salary/(?P<name>\w+)/$', views.driver_salary, name='driver_salary'),
    url(r'^driver_salary_list/$', views.driver_salary_list, name='driver_salary_list'),
    url(r'^saler_salary/(?P<name>\w+)/$', views.saler_salary, name='saler_salary'),
    url(r'^saler_salary_list/$', views.saler_salary_list, name='saler_salary_list'),
    url(r'^ajax_by_year/$', views.ajax_by_year, name='ajax_by_year'),
]

account/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    date_of_birth = models.DateField("出生日期",blank=True, null=True)
    photo = models.ImageField('头像路径',upload_to='users/%Y/%m/%d', blank=True)

    class Meta:
        verbose_name_plural = "用户简介"

    def __str__(self):
        return 'Profile for user {}'.format(self.user.username)

account/forms.py
#! /usr/bin/env python
# -*- coding:utf-8 -*-
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class LoginForm(forms.Form):
    username = forms.CharField(label="用户名",max_length=15,error_messages={"required":"用户名不能为空"})
    password = forms.CharField(label="密码" , widget=forms.PasswordInput, max_length=15, min_length=6,error_messages={"required":"密码不能为空"})

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label="密码",widget=forms.PasswordInput, max_length=15)
    password2 = forms.CharField(label="确认密码",widget=forms.PasswordInput, max_length=15)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')
    def clean_password2(self):
        cd = self.cleaned_data
        if cd["password"] != cd["password2"]:
            raise forms.ValidationError("密码不匹配")
        return cd["password2"]

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth','photo')

account/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from .forms import LoginForm
from django.contrib.auth.decorators import login_required
from .forms import LoginForm, UserRegistrationForm, UserEditForm, ProfileEditForm
from .models import Profile

from django.contrib import messages

# Create your views here.
def user_login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd["username"],password=cd['password'])
            if user is not None:
                if user.is_active: #如果用户帐户当前处于活动状态，则返回 True。
                    login(request, user)
                    return HttpResponse("认证成功")
                else:
                    return HttpResponse('账户不可用')
    else:
        form = LoginForm()
    return render(request, 'account/login.html', {'form':form})

@login_required
def dashboard(request):
    return render(request, 'account/dashboard.html',{"section":"dashboard"})

def register(request):
    if request.method == "POST":
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            cd = user_form.cleaned_data
            new_user = user_form.save(commit=False)
            new_user.set_password(cd["password"])
            new_user.save()
            profile = Profile.objects.create(user=new_user)
            return render(request, 'account/register_done.html', {"new_user":new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'account/register.html', {"user_form":user_form})

@login_required
def edit(request):
    if request.method == "POST":
        print("=" * 30)
        print("request:",request)
        print(request.user.profile)
        print("="*30)
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile, data=request.POST, files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, '简介更新成功')
            return render(request, "account/ajax.html")
        else:
            messages.error(request, '更新简介失败')
            return render(request, "account/ajax.html")
    else:
        print("=" * 30)
        print("request.user:",request.user)
        print(dir(request.user))
        print(request.user.profile)
        print("="*30)
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    return render(request, 'account/edit.html', {"user_form":user_form,"profile_form":profile_form})

account/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.bootcss.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="http://cdn.bootcss.com/font-awesome/4.6.2/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="/static/css/base.css" />
    <title>{% block title %}{% endblock %}</title>
 <style type="text/css">
@import url(http://fonts.googleapis.com/css?family=Muli);
body {
    margin:0;
    padding:0;
    font-family:helvetica, sans-serif;
}
p {
    line-height: 1.8;
}
a {
    color:#12c064;
    text-decoration:none;
}
a:hover {
    color:#00a74f;
}
h1, h2, h3, h4, h5 , h6 { font-family: 'Muli', sans-serif; font-weight:normal; }
h1 {
    border-bottom:1px solid #bbb;
    padding:0 0 10px 0;
    margin:10px 0 20px 0;
}
h2 {
    margin:30px 0 20px;
}
ol {
    line-height:1.5;
}
#header {
    padding:10px 100px;
    font-size:14px;
    background:#12c064;
    color:#fff;
    border-bottom:4px solid #1cdf78;
    overflow:auto;
}
#header .logo {
    font-family: 'Muli', sans-serif;
    float:left;
    color:#f3f7cc;
    font-size:20px;
    margin-right:10%;
}
#header ul.menu {
    list-style:none;
    float:left;
    margin:0;
    padding:0;
}
#header ul.menu li {
    float:left;
    padding:4px 10px;
}
#header ul.menu li.selected a, #header ul.menu li.selected a:hover {
    color:#1b6d32;
    font-weight:bold;
}
#header a {
    color:#f3f7cc;
}
#header a:hover {
    color:#fff;
}
#header .user {
    float:right;
    padding-top:4px;
}
#content {
    padding:30px 100px;
}
/* forms */
form {
    overflow:auto;
}
form p {
    width:100%;
    overflow:auto;
}
label {
    float:left;
    clear:both;
    color:#333;
    margin-bottom:4px;
}
input, textarea {
    clear:both;
    float:left;
    margin:0 0 10px;
    background:#efefef;
    border:0;
    padding:6px 10px;
    font-size:14px;
}
input[type=submit], a.button {
    font-weight:bold;
    background:#12c064;
    color:#fff;
    padding:10px 20px;
    font-size:14px;
    text-transform:uppercase;
}
.errorlist {
    color:#cc0033;
    float:left;
    clear:both;
    padding-left:10px;
}
.helptext {
    margin:0 0 20px 0;
    color:#aaa;
    clear:both;
    float:left;
    font-size:13px;
}
/* messages */
ul.messages {
    margin:10px 100px;
    padding:0;
    list-style-type:
    none;
}
ul.messages li.success,
ul.messages li.warning,
ul.messages li.error,
ul.messages li.info {
    margin:0;
    padding:14px 20px;
    list-style:none;
    color:#fff;
}
ul.messages li.success { background:#81ce81; }
ul.messages li.success a { color:#0ac33e; }
ul.messages li.error { background:#a30029; color:#e9828e; }
ul.messages li.error a { color:#e9828e; }
ul.messages li.info { background:#faffae; color:#696b4e; }
ul.messages li.info a { color:#1586de; }
ul.messages li.warning { background:#de9404; }
ul.messages li.warning a { color:#f49000; }
ul.messages li a.close {
    margin:0;
    float:right;
    opacity:1;
    border:0;
    box-shadow:none;
    text-shadow:none;
}
.login-form {
    float:left;
}
/* social-auth */
.social {
    float:right;
}
.social li {
    list-style:none;
    padding:10px 20px;
    margin:0 0 10px 0;
}
.social li a {
    width:100%;
    height:100%;
    display:block;
    color:#fff;
}
.social li.facebook { background:#3b5399; }
.social li.twitter { background:#00cffa; }
.social li.google { background:#de1710; }
/* images */
.image-preview, .image-detail {
    max-width:300px;
    float:left;
    margin:0 20px 20px 0;
}
.image-detail { margin-top:20px; }
.image-info div {
    padding:20px 0;
    overflow:auto;
}
.count {
    color:#aaa;
    border:3px solid #bbb;
    border-radius:26px;
    padding:10px 20px;
    margin:20px 10px 0;
}
a.like, a.follow { float:right; margin-top:-8px; }
#image-list { overflow:auto; }
#image-list .image {
    float:left;
    width:220px;
    height:300px;
    margin:0 10px 10px 10px;
    border-top:8px solid #12c064;
    background:#eee;
}
#image-list img { width:220px; height:220px; }
#image-list .info { padding:10px; }
#image-list .info a { color:#333; }
.image-likes div {
    float:left;
    width:auto;
    padding:10px;
    text-align:center;
}
.image-likes img {
    width:120px;
    height:120px;
    border-radius:50%;
}
/* users */
#people-list img {
    width:180px;
    height:180px;
    border-radius:50%;
    margin-bottom:20px;
}
#people-list .user {
    width:180px;
    float:left;
    overflow:auto;
    padding:10px;
}
#people-list .info { text-align:center; }
img.user-detail {
    border-radius:50%;
    float:left;
}
.profile-info {
    float:left;
    overflow:auto;
    margin-right:20px;
}
.image-container { margin-top:40px; }
/* actions */
.action {
    clear:both;
    overflow:auto;
}
.action .images {
    float:left;
    margin:0 10px 10px 0;
}
.action .date {
    font-style:italic;
    color:#ccc;
}
    </style>
</head>
<body>
    <div id="header">
        <span class="logo">车辆运行管理系统</span>
        {% if request.user.is_authenticated %}
            <ul class="menu">
                <li {% if section == 'dashboard' %} class='selected' {% endif %} >
                    <a href="{% url 'car:car_index' %}">车辆管理系统主页</a>
                </li>
           
                <li {% if section == "driver" %} class="selected"{% endif %}>
                    <a href="/car/driver/">司机</a>
                </li>
                <li {% if section == "saler" %} class="selected"{% endif %}>
                    <a href="/car/saler/">售票员</a>
                </li>
            </ul>
        {% endif %}
        <span class="user">
            {% if request.user.is_authenticated %}
                Hello <a href="{% url 'edit' %}">{{ request.user.username }}</a>
                <a href="{% url 'logout' %}">退出登陆</a>
            {% else %}
                <a href="{% url 'login' %}">登陆</a>
            {% endif %}
        </span>
    </div>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>
<script src="https://cdn.bootcss.com/jquery/2.2.4/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>