bus/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include("account.urls")),
    url(r'^car/', include("car.urls",namespace="car")),
    url(r'^$', RedirectView.as_view(url='/account/login/'),),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = "车辆管理系统后台"

car/urls.py
#! /usr/bin/env python
# -*- coding:utf-8 -*-

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^car_index/$',views.test),
    url(r'^car_index/$', views.CarView.as_view(), name='car_index'),
    # url(r'^car_create/$', views.car_create, name='car_create'),
    url(r'^car_create_ajax/$', views.car_create_ajax, name='car_create_ajax'),
    url(r'^car_detail_ajax/$', views.car_detail_ajax, name='car_detail_ajax'),
    url(r'^get_car_info_ajax/$', views.get_car_info_ajax, name='get_car_info_ajax'),
    url(r'^car_search/$', views.CarSearchView.as_view(), name='car_search'),
    url(r'^static_car/$', views.static_car, name='static_car'),
    url(r'^car_by_year/$', views.car_by_year, name='car_by_year'),
    url(r'^car_by_month/$', views.car_by_month, name='car_by_month'),
    url(r'^car_by_day/$', views.car_by_day, name='car_by_day'),
    url(r'^car_by_year_detail/(?P<year>\d{4})/$', views.car_by_year_detail, name='car_by_year_detail'),
    url(r'^car_by_month_detail/(?P<year>\d{4})/(?P<month>\d{1,})/$', views.car_by_month_detail, name='car_by_month_detail'),
    url(r'^car_by_day_detail/(?P<year>\d{4})/(?P<month>\d{1,})/(?P<day>\d{1,})/$', views.car_by_day_detail, name='car_by_day_detail'),
    url(r'^static_car_month/(?P<year>\d{4})/(?P<month>\d{1,})/$', views.static_car_month, name='static_car_month'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,})/(?P<day>\d{1,})/(?P<name>[-\w]+)/$', views.car_detail, name="car_detail"),
    url(r'^driver/$', views.driver, name='driver'),
    url(r'^saler/$', views.saler, name='saler'),
    url(r'^driver_salary/(?P<name>\w+)/$', views.driver_salary, name='driver_salary'),
    url(r'^driver_salary_list/$', views.driver_salary_list, name='driver_salary_list'),
    url(r'^saler_salary/(?P<name>\w+)/$', views.saler_salary, name='saler_salary'),
    url(r'^saler_salary_list/$', views.saler_salary_list, name='saler_salary_list'),
    url(r'^ajax_by_year/$', views.ajax_by_year, name='ajax_by_year'),
]

car/forms.py
#! /usr/bin/env python
# -*- coding:utf-8 -*-
from django import forms
from .models import Car


class CarForm(forms.Form):
    name = forms.CharField(label="车名",error_messages={"required":"车名不能为空"})
    driver = forms.CharField(label="司机",error_messages={"required":"司机不能为空"})
    saler = forms.CharField(label="售票员",error_messages={"required":"售票员不能为空"})
    people_30 = forms.CharField(label="30元票价人数",widget=forms.NumberInput,required=False)
    people_40 = forms.CharField(label="40元票价人数",widget=forms.NumberInput,required=False)
    things = forms.CharField(label="货钱",widget=forms.NumberInput,required=False)
    food = forms.CharField(label="饭钱及其他额外花销",widget=forms.NumberInput,required=False)
    oil = forms.CharField(label="油钱",widget=forms.NumberInput,required=False)

    def clean_people_30(self):
        people_30 = self.cleaned_data.get("people_30",0)
        if people_30:
            if int(people_30) >= 60:
                raise forms.ValidationError("30元人数填写错误，不能高于60")
        return people_30

    def clean_people_40(self):
        people_40 = self.cleaned_data.get("people_40",0)
        if people_40:
            if int(people_40) >= 60:
                raise forms.ValidationError("40元人数填写错误，不能高于60")
        return people_40

    def clean_oil(self):
        oil = self.cleaned_data.get("oil",0)
        if not oil:
            oil = 0
        return oil

class DateForm(forms.Form):
    date = forms.DateField(label='运营月份',error_messages={"required":"月份不能为空"})

class RealMoneyForm(forms.Form):
    money = forms.IntegerField(label='实际收入金额',required=False)

car/views.py
from django.shortcuts import render
from .models import Car,Saler,SalerSalary,Driver,DriverSalary
from .forms import CarForm, DateForm,RealMoneyForm
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, get_list_or_404
from django.shortcuts import reverse
from datetime import datetime
import json
# Create your views here.

from django.core.paginator import Paginator
from django.views.generic import View, TemplateView, ListView

def test(request):
    print("request",request.POST)
    return HttpResponse("ok")

#解释说明：
"""
TemplateView自带的有一个GET请求的方法，返回的网页就是template_name = "user/userlist.html"，网页里面的传的数据内容可以通过重写get_context_data这个方法来获取，django自己写分页的话是利用列表的切片，类似于mysql的limit和offset，这里是引用自带的分页模块
"""
class CarView(TemplateView):
    template_name = "car/car_index.html"
    def get_context_data(self, **kwargs):
        #这个方法就可以将变量传到模板里
        context = super(CarView, self).get_context_data(**kwargs)
        try:
            page = int(self.request.GET.get("page","1")) #这里做了异常处理，如果page是字符，就会变成下面的page=1
        except:
            page = 1
        paginator = Paginator(Car.objects.all(),10)
        page_obj = paginator.page(page) #这个page_obj是为了和自带的方法保持一致
        context["object_list"] = page_obj.object_list # page_obj.object_list是要获得的
        context["page_obj"] = page_obj # page_obj 也是要获得的
        return context



def car_detail(request, year, month, day, name):
    car = get_object_or_404(Car,slug=name,\
                            date__year=year,\
                            date__month=month,\
                            date__day=day)
    content = {'car':car}
    return render(request,'car/car_detail.html',content)

from django.views.decorators.csrf import csrf_exempt
@csrf_exempt
def car_detail_ajax(request):
    if request.method == "POST":
        print("post")
        money = float(request.POST.get("money",0).strip())
        real_income = float(request.POST.get("real_income",0).strip())
        warning = '''
        <div class="alert alert-warning alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <strong>警告!</strong> <strong>实际金额低</strong>于应有收入，请核对看是否有问题.
</div>
        '''
        well = '''
        <div class="alert alert-success alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <strong>警告!</strong> <strong>实际金额高</strong>于应有收入，请核对看是否有问题.
</div>
        '''
        normal = '''
        <div class="alert alert-info alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <strong>正确!</strong> 实际金额等于应有收入，账单没什么问题.
</div>
        '''
        if money < real_income:
            return HttpResponse(warning)
        elif money > real_income:
            return HttpResponse(well)
        else:
            return HttpResponse(normal)
    print("get")
    return render(request,'car/car_detail.html')

#
# def car_create(request):
#     if request.method == "POST":
#         form = CarForm(request.POST,initial={"name":""})
#         print("POST")
#         if form.is_valid():
#             cd = form.cleaned_data
#             name = cd.get("name","")
#             driver = cd.get("driver","")
#             d = get_object_or_404(Driver,name__contains =driver)
#             saler = cd.get("saler","")
#             s = get_object_or_404(Saler, name__contains=saler)
#             people_30 = int(cd.get("people_30",0))
#             people_40 = int(cd.get("people_40",0))
#             food = cd.get("food",0)
#             things = cd.get("things",0)
#             oil = int(cd.get("oil",0))
#             total_income = int(people_40)*40+int(people_30)*30+int(things)
#             real_income = int(people_40)*40+int(people_30)*30+int(things)-int(food)
#             total_people = int(people_30)+int(people_40)
#             car = Car(name=name,total_income=total_income,oil=oil,total_people=total_people,\
#                       real_income=real_income,saler=s,driver=d,people_30=people_30,\
#                       people_40=people_40,food=food,things=things)
#             car.save()
#             print(cd)
#             return HttpResponseRedirect(reverse('car:car_index'))
#     else:
#         form = CarForm(initial={"name":""})
#     return render(request, "car/run_create.html",{'form':form})

# ajax创建车辆每日运行信息
def car_create_ajax(request):
    form = CarForm(request.POST)
    if form.is_valid():
        print("POST")
        cd = form.cleaned_data
        name = cd.get("name","")
        driver = cd.get("driver","")
        d = get_object_or_404(Driver,name__contains =driver)
        saler = cd.get("saler","")
        s = get_object_or_404(Saler, name__contains=saler)
        people_30 = int(cd.get("people_30",0))
        people_40 = int(cd.get("people_40",0))
        food = cd.get("food",0)
        things = cd.get("things",0)
        oil = int(cd.get("oil",0))
        total_income = int(people_40)*40+int(people_30)*30+int(things)
        real_income = int(people_40)*40+int(people_30)*30+int(things)-int(food)
        total_people = int(people_30)+int(people_40)
        car = Car(name=name,total_income=total_income,oil=oil,total_people=total_people,\
                  real_income=real_income,saler=s,driver=d,people_30=people_30,\
                  people_40=people_40,food=food,things=things)
        car.save()
        return JsonResponse({"status":200,"result":""})
    else:
        return JsonResponse({"status":400,'result':"",'errors':json.loads(form.errors.as_json())})

# 使用DataTable插件获取车辆信息
def get_car_info_ajax(request):
    cars = Car.objects.all()
    cars = [ car.as_dict() for car in cars]
    return JsonResponse({"data":cars})

#通过ajax获取每年的运营数据
def ajax_by_year(request):
    year = request.GET.get("year","2017")
    year_data = get_list_or_404(Car,date__year=year) #某一年的所有车辆数据
    dict_month = {}#该年的每个月的车辆的数据，月份为key，数据为value
    for i in year_data:
        # dict_month[i.date.month] = dict_month.get(i.date.month,[])+[(i.total_income,i.oil)]
        if i.date.month in dict_month:
            dict_month.get(i.date.month).append(((i.name,i.total_income,i.oil)))
        else:
            dict_month.setdefault(i.date.month,[(i.name,i.total_income,i.oil)])
    print(dict_month)
    dict_car ={}
    for m in dict_month:
        dict_car[m] ={}
        print('m','-->',m)
        for c in dict_month[m]:
            print('c','-->',c)
            if c[0] in dict_car[m]:
                print(dict_car[m],"-->",c)
                dict_car[m][c[0]] = (dict_car[m][c[0]][0]+c[1],dict_car[m][c[0]][1]+c[2])
            else:
                dict_car[m][c[0]] = (c[1],c[2])
    print('sum','-->',dict_car)
    return JsonResponse(dict_car)


from django.db.models import Q

class CarSearchView(TemplateView):
    template_name = "car/car_search.html"

    def get_context_data(self, **kwargs):
        #这个方法就可以将变量传到模板里
        context = super(CarSearchView, self).get_context_data(**kwargs)
        try:
            page = int(self.request.GET.get("page","1")) #这里做了异常处理，如果page是字符，就会变成下面的page=1
        except:
            page = 1
        keywords = self.request.GET.get("search", "")
        search_all = get_list_or_404(Car, Q(name__contains=keywords) | Q(driver__name__contains=keywords)|Q(saler__name__contains=keywords))
        print(search_all)
        paginator = Paginator(search_all,1)
        page_obj = paginator.page(page) #这个page_obj是为了和自带的方法保持一致
        context["object_list"] = page_obj.object_list # page_obj.object_list是要获得的
        context["page_obj"] = page_obj # page_obj 也是要获得的
        context['keywords'] = keywords
        return context

def static_car(request):
    if request.method == "POST":
        form = DateForm(request.POST, initial={"date":datetime.today()})
        if form.is_valid():
            cd = form.cleaned_data
            date_str = request.POST.get('date',datetime.today())
            print("date",date_str)
            date = datetime.strptime(date_str,'%Y-%m-%d')
            year = date.year
            month = date.month
            month_all = get_list_or_404(Car, date__year=year, date__month=month)
            print(month_all)
            return HttpResponseRedirect(reverse('car:static_car_month', args=(year,month)))
    else:
        form = DateForm()
    return render(request,"car/static_car.html",{"form":form})

def static_car_month(request,year,month):
    month_all = get_list_or_404(Car, date__year=year, date__month=month)
    try:
        page = int(request.GET.get("page", "1"))  # 这里做了异常处理，如果page是字符，就会变成下面的page=1
    except:
        page = 1
    paginator = Paginator(month_all, 3)
    page_obj = paginator.page(page)  # 这个page_obj是为了和自带的方法保持一致
    context = {}
    context["object_list"] = page_obj.object_list  # page_obj.object_list是要获得的
    context["page_obj"] = page_obj  # page_obj 也是要获得的
    return render(request, 'car/static_car_month.html', context)

#按年分
def car_by_year(request):
    year_all = Car.objects.all()
    years = list(set([i.date.year for i in year_all]))

    try:
        page = int(request.GET.get("page", "1"))  # 这里做了异常处理，如果page是字符，就会变成下面的page=1
    except:
        page = 1
    print(years)
    paginator = Paginator(years, 3)
    page_obj = paginator.page(page)  # 这个page_obj是为了和自带的方法保持一致
    context = {}
    context["object_list"] = page_obj.object_list  # page_obj.object_list是要获得的
    context["page_obj"] = page_obj  # page_obj 也是要获得的
    return render(request, 'car/car_by_year.html', context)

def car_by_year_detail(request,year):

car/templates/car/car_by_day_detail.html
{% extends 'carbase.html' %}

{% block title %}
车辆信息详细页
{% endblock %}

{% block nav_day %}
    class="active"
{% endblock %}

{% block content %}
<h1>车辆{{ month }}月{{ day }}日运营信息</h1>
    <a href="{% url 'car:car_index' %}"><i class="fa fa-university"></i></a>
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr style="background-color: #CAE1FF;">
                <th>时间</th>
                <th>总收入</th>
                <th>净收入</th>
                <th>总人数</th>
                <th>油钱</th>
                <th>30元票价人数</th>
                <th>40元票价人数</th>
                <th>货钱</th>
                <th>饭钱及其他额外花销</th>
            </tr>
        </thead>
        <tbody>
                <tr>
                    <td>{{ year }}年{{ month }}月{{ day }}日</td>
                    <td>{{ total_income }} 元</td>
                    <td>{{ real_income }} 元</td>
                    <td>{{ total_people }} 人</td>
                    <td>{{ oil }} 元</td>
                    <td>{{ people_30 }} 人</td>
                    <td>{{ people_40 }} 人</td>
                    <td>{{ things }} 元</td>
                    <td>{{ food }} 元</td>
                </tr>
        </tbody>
    </table>

每辆车的全年运营信息：
        <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr style="background-color: #CAE1FF;">
                <th>时间</th>
                <th>车名</th>
                <th>总收入</th>
                <th>净收入</th>
                <th>总人数</th>
                <th>油钱</th>
                <th>30元票价人数</th>
                <th>40元票价人数</th>
                <th>货钱</th>
                <th>饭钱及其他额外花销</th>
            </tr>
        </thead>
        <tbody>
            {% for car in names %}
                <tr>
                    <td>{{ car.year }}年{{ car.month }}月{{ car.day }}日</td>
                    <td>豫A {{ car.name }}</td>
                    <td>{{ car.total_income }} 元</td>
                    <td>{{ car.real_income }} 元</td>
                    <td>{{ car.total_people }} 人</td>
                    <td>{{ car.oil }} 元</td>
                    <td>{{ car.people_30 }} 人</td>
                    <td>{{ car.people_40 }} 人</td>
                    <td>{{ car.things }} 元</td>
                    <td>{{ car.food }} 元</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

car/templates/car/car_by_month.html
{% extends 'carbase.html' %}
{% block title %}
按月份查看
{% endblock %}
{% block nav_month %}
    class="active"
{% endblock %}
{% block content %}
<h1>车辆选择月份的汇总信息</h1>
    <a href="{% url 'car:car_index' %}"><i class="fa fa-university"></i></a>
    <table id="table" class="table table-striped table-hover">
        <thead>
            <tr style="background-color: #CAE1FF;">
                <th>日期(月份)</th>
            </tr>
        </thead>
        <tbody>
            {% for year_month in object_list %}
                <tr>
                    <td><a class="btn btn-default" href="{% url 'car:car_by_month_detail' year_month.0 year_month.1 %}" role="button">{{ year_month.0 }}年{{ year_month.1 }}月</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
                    <!--分页-->
        <nav aria-label="Page navigation">
          <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li><a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                {% endif %}
              {% for num in page_obj.paginator.page_range %}
                  {% if page_obj.number == num %}
                      <li class="active"><a href="#">{{ num }}<span class="sr-only">(current)</span></a></li>
                  {% else %}
                      <li><a href="?page={{ num }}">{{ num }}</a></li>
                  {% endif %}
              {% endfor %}
              {% if page_obj.has_next %}
                  <li>
                    <a href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span></a></li>
              {% endif %}
          </ul>
        </nav>
{% endblock %}

car/templates/car/car_by_month_detail.html
{% extends 'carbase.html' %}

{% block title %}
车辆信息详细页
{% endblock %}

{% block nav_month %}
    class="active"
{% endblock %}

{% block content %}
<h1>车辆{{ month }}月运营信息</h1>
    <a href="{% url 'car:car_index' %}"><i class="fa fa-university"></i></a>
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr style="background-color: #CAE1FF;">
                <th>时间</th>
                <th>总收入</th>
                <th>净收入</th>
                <th>总人数</th>
                <th>油钱</th>
                <th>30元票价人数</th>
                <th>40元票价人数</th>
                <th>货钱</th>
                <th>饭钱及其他额外花销</th>
            </tr>
        </thead>
        <tbody>
                <tr>
                    <td>{{ year }}年{{ month }}月</td>
                    <td>{{ total_income }} 元</td>
                    <td>{{ real_income }} 元</td>
                    <td>{{ total_people }} 人</td>
                    <td>{{ oil }} 元</td>
                    <td>{{ people_30 }} 人</td>
                    <td>{{ people_40 }} 人</td>
                    <td>{{ things }} 元</td>
                    <td>{{ food }} 元</td>
                </tr>
        </tbody>
    </table>

每辆车的全年运营信息：
        <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr style="background-color: #CAE1FF;">
                <th>时间</th>
                <th>车名</th>
                <th>总收入</th>
                <th>净收入</th>
                <th>总人数</th>
                <th>油钱</th>
                <th>30元票价人数</th>
                <th>40元票价人数</th>
                <th>货钱</th>
                <th>饭钱及其他额外花销</th>
            </tr>
        </thead>
        <tbody>
            {% for car in names %}
                <tr>
                    <td>{{ car.year }}年{{ car.month }}月</td>
                    <td>豫A {{ car.name }}</td>
                    <td>{{ car.total_income }} 元</td>
                    <td>{{ car.real_income }} 元</td>
                    <td>{{ car.total_people }} 人</td>
                    <td>{{ car.oil }} 元</td>
                    <td>{{ car.people_30 }} 人</td>
                    <td>{{ car.people_40 }} 人</td>
                    <td>{{ car.things }} 元</td>
                    <td>{{ car.food }} 元</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

car/templates/car/car_by_year.html
{% extends 'carbase.html' %}

{% block title %}
按年份查看
{% endblock %}
{% block nav_year %}
    class="active"
{% endblock %}
{% block content %}
<h1>车辆选择年份的汇总信息</h1>
    <a href="{% url 'car:car_index' %}"><i class="fa fa-university"></i></a>
    <table id="table" class="table table-striped table-hover">
        <thead>
            <tr style="background-color: #CAE1FF;">
                <th>日期(年份)</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for year in object_list %}
                <tr>
                    <td><a class="btn btn-default" href="{% url 'car:car_by_year_detail' year %}" role="button">{{ year }}</a></td>
                    <td><a id='plot' class="btn btn-default" href="#" role="button">图形展示</a></td>
{#                    <td><button id="{{ year }}" class="btn btn-default">图形展示</button></td>#}
                </tr>
            {% endfor %}
        </tbody>
    </table>
                    <!--分页-->
        <nav aria-label="Page navigation">
          <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li><a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                {% endif %}
              {% for num in page_obj.paginator.page_range %}
                  {% if page_obj.number == num %}
                      <li class="active"><a href="#">{{ num }}<span class="sr-only">(current)</span></a></li>
                  {% else %}
                      <li><a href="?page={{ num }}">{{ num }}</a></li>
                  {% endif %}
              {% endfor %}
              {% if page_obj.has_next %}
                  <li>
                    <a href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span></a></li>
              {% endif %}
          </ul>
        </nav>
        {#  展示分析图  #}
        <div id="main" style="width: 800px;height: 400px">车辆收入分析堆叠图</div>
    <script type="text/javascript" src="https://cdn.bootcss.com/jquery/2.2.4/jquery.min.js" ></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $("#plot").on("click",function () {
                console.log("ajax开始");
                $.get("/car/ajax_by_year/?year=2017",function(data){
                    var month_0 = data[0];
                    var month_1 = data[1];
                    var month_2 = data[2];
                    var month_3 = data[3];
                    var month_4 = data[4];
                    var month_5 = data[5];
                    var month_6 = data[6];
                    var month_7 = data[7];
                    var month_8 = data[8];
                    var month_9 = data[9];
                    var month_10 = data[10];
                    var month_11 = data[11];
                    var month_12 = data[12];
                    var obj ={"month_0":month_0,"month_1":month_1,"month_2":month_2,"month_3":month_3,
                        "month_4":month_4,"month_5":month_5,"month_6":month_6,"month_7":month_7,"month_8":month_8
                    ,"month_9":month_9,"month_10":month_10,"month_11":month_11,"month_12":month_12};
                    console.log("data",data);
                    var data_list = [];
                    var data_obj = [];
                    var data_car_obj = {};
                    for(var i=1;i<13;i++){
                        if(data[i]){
                            data_list.push(i+"月");
                            data_obj.push(obj["month_"+i]);
                        }
                    }
{#                    for(var i in data_obj){#}
{#                        console.log("月份：",data_obj[i]);#}
{#                    }#}
                    var car_name = ['2287','5658','9809']
                    for(var i in car_name){
                        data_car_obj[car_name[i]] = [];
{#                        console.log(car_name[i]);#}
                    }
                    for(var m in data_obj){
                        for(var c in car_name){
                            data_car_obj[car_name[c]].push(data_obj[m][car_name[c]][0])
{#                            console.log('car:',data_car_obj[car_name[c]])#}
{#                            console.log("detail:",data_obj[m][car_name[c]])#}
                        }
                    }

                    console.log("detail:",data_car_obj['2287']);
                    var series_list = []
                    for(var i in car_name){
                        var one_data = {
                                name:'豫A '+car_name[i],
                                type:'line',
                                stack: '总量',
                                data:data_car_obj[car_name[i]]
                            };
                        series_list.push(one_data);
                    }
                    console.log("series_list:",series_list);
                    console.log(data_list);
                    console.log(data_obj);
                    var myChart = echarts.init(document.getElementById('main'));
                    var option = {
                        title: {
                            text: '车辆2017年运营汇总'
                        },
                        tooltip: {
                            trigger: 'axis'
                        },
                        legend: {
                            data:['豫A 2287','豫A 5658','豫A 9809']
                        },
                        grid: {
                            left: '3%',
                            right: '4%',
                            bottom: '3%',
                            containLabel: true
                        },
                        toolbox: {
                            feature: {
                                saveAsImage: {}
                            }
                        },
                        xAxis: {
                            type: 'category',
                            boundaryGap: false,
                            data: data_list
                        },
                        yAxis: {
                            type: 'value'
                        },
                        series: series_list
                    };

                    // 使用刚指定的配置项和数据显示图表
                    myChart.setOption(option);
                },"json")
            })
        })
    </script>
{% endblock %}

car/templates/car/driver.html
{% extends 'carbase.html' %}

{% block title %}
司机信息详细页
{% endblock %}

{% block nav_driver %}
    class="active"
{% endblock %}

{% block content %}
<h1>司机信息详列表</h1>
    <a href="{% url 'car:car_index' %}"><i class="fa fa-university"></i></a>
        <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr style="background-color: #CAE1FF;">
                <th>姓名</th>
                <th>薪资情况</th>
            </tr>
        </thead>
        <tbody>
            {% for driver in object_list %}
                <tr>
                    <td>{{ driver.name }}</td>
                    <td><a href="{% url 'car:driver_salary' driver.name %}">{{ driver.name }}的薪资详细信息</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

car/templates/car/saler.html
{% extends 'carbase.html' %}

{% block title %}
售票员信息详细页
{% endblock %}

{% block nav_saler %}
    class="active"
{% endblock %}

{% block content %}
<h1>售票员信息详细列表</h1>
    <a href="{% url 'car:car_index' %}"><i class="fa fa-university"></i></a>
        <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr style="background-color: #CAE1FF;">
                <th>姓名</th>
                <th>薪资情况</th>
            </tr>
        </thead>
        <tbody>
            {% for saler in object_list %}
                <tr>
                    <td>{{ saler.name }}</td>
                    <td><a href="{% url 'car:saler_salary' saler.name %}">{{ saler.name }}的薪资详细信息</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

car/templates/car/saler_salary.html
{% extends 'carbase.html' %}

{% block title %}
售票员薪资信息详细页
{% endblock %}

{% block nav_salersalary %}
    class="active"
{% endblock %}

{% block content %}
    <h1>售票员<strong>{{ name }}</strong>薪资信息详细页</h1>
    <a href="{% url 'car:car_index' %}"><i class="fa fa-university"></i></a>
        <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr style="background-color: #CAE1FF;">
                <th>姓名</th>
                <th>时间</th>
                <th>应有工资</th>
                <th>借钱</th>
                <th>实际工资</th>
                <th>请假开始日期</th>
                <th>请假天数</th>
                <th>请假原因</th>
            </tr>
        </thead>
        <tbody>
            {% for saler in object_list %}
                <tr>
                    <td>{{ saler.name.name }}</td>
                    <td>{{ saler.date |date:'Y-m-d' }}</td>
                    <td>{{ saler.salary }}</td>
                    <td>{{ saler.borrow }}</td>
                    <td>{{ saler.real_salary }}</td>
                    <td>{{ saler.time|date:'Y-m-d' }}</td>
                    <td>{{ saler.days }}</td>
                    <td>{{ saler.reason|slice:":8" }}...</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}