bus/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include("account.urls")),
    url(r'^car/', include("car.urls",namespace="car")),
    url(r'^$', RedirectView.as_view(url='/account/login/'),),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = "车辆管理系统后台"

car/urls.py
#! /usr/bin/env python
# -*- coding:utf-8 -*-

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^car_index/$',views.test),
    url(r'^car_index/$', views.CarView.as_view(), name='car_index'),
    # url(r'^car_create/$', views.car_create, name='car_create'),
    url(r'^car_create_ajax/$', views.car_create_ajax, name='car_create_ajax'),
    url(r'^car_detail_ajax/$', views.car_detail_ajax, name='car_detail_ajax'),
    url(r'^get_car_info_ajax/$', views.get_car_info_ajax, name='get_car_info_ajax'),
    url(r'^car_search/$', views.CarSearchView.as_view(), name='car_search'),
    url(r'^static_car/$', views.static_car, name='static_car'),
    url(r'^car_by_year/$', views.car_by_year, name='car_by_year'),
    url(r'^car_by_month/$', views.car_by_month, name='car_by_month'),
    url(r'^car_by_day/$', views.car_by_day, name='car_by_day'),
    url(r'^car_by_year_detail/(?P<year>\d{4})/$', views.car_by_year_detail, name='car_by_year_detail'),
    url(r'^car_by_month_detail/(?P<year>\d{4})/(?P<month>\d{1,})/$', views.car_by_month_detail, name='car_by_month_detail'),
    url(r'^car_by_day_detail/(?P<year>\d{4})/(?P<month>\d{1,})/(?P<day>\d{1,})/$', views.car_by_day_detail, name='car_by_day_detail'),
    url(r'^static_car_month/(?P<year>\d{4})/(?P<month>\d{1,})/$', views.static_car_month, name='static_car_month'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,})/(?P<day>\d{1,})/(?P<name>[-\w]+)/$', views.car_detail, name="car_detail"),
    url(r'^driver/$', views.driver, name='driver'),
    url(r'^saler/$', views.saler, name='saler'),
    url(r'^driver_salary/(?P<name>\w+)/$', views.driver_salary, name='driver_salary'),
    url(r'^driver_salary_list/$', views.driver_salary_list, name='driver_salary_list'),
    url(r'^saler_salary/(?P<name>\w+)/$', views.saler_salary, name='saler_salary'),
    url(r'^saler_salary_list/$', views.saler_salary_list, name='saler_salary_list'),
    url(r'^ajax_by_year/$', views.ajax_by_year, name='ajax_by_year'),
]

car/forms.py
#! /usr/bin/env python
# -*- coding:utf-8 -*-
from django import forms
from .models import Car


class CarForm(forms.Form):
    name = forms.CharField(label="车名",error_messages={"required":"车名不能为空"})
    driver = forms.CharField(label="司机",error_messages={"required":"司机不能为空"})
    saler = forms.CharField(label="售票员",error_messages={"required":"售票员不能为空"})
    people_30 = forms.CharField(label="30元票价人数",widget=forms.NumberInput,required=False)
    people_40 = forms.CharField(label="40元票价人数",widget=forms.NumberInput,required=False)
    things = forms.CharField(label="货钱",widget=forms.NumberInput,required=False)
    food = forms.CharField(label="饭钱及其他额外花销",widget=forms.NumberInput,required=False)
    oil = forms.CharField(label="油钱",widget=forms.NumberInput,required=False)

    def clean_people_30(self):
        people_30 = self.cleaned_data.get("people_30",0)
        if people_30:
            if int(people_30) >= 60:
                raise forms.ValidationError("30元人数填写错误，不能高于60")
        return people_30

    def clean_people_40(self):
        people_40 = self.cleaned_data.get("people_40",0)
        if people_40:
            if int(people_40) >= 60:
                raise forms.ValidationError("40元人数填写错误，不能高于60")
        return people_40

    def clean_oil(self):
        oil = self.cleaned_data.get("oil",0)
        if not oil:
            oil = 0
        return oil

class DateForm(forms.Form):
    date = forms.DateField(label='运营月份',error_messages={"required":"月份不能为空"})

class RealMoneyForm(forms.Form):
    money = forms.IntegerField(label='实际收入金额',required=False)

car/views.py
from django.shortcuts import render
from .models import Car,Saler,SalerSalary,Driver,DriverSalary
from .forms import CarForm, DateForm,RealMoneyForm
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, get_list_or_404
from django.shortcuts import reverse
from datetime import datetime
import json
# Create your views here.

from django.core.paginator import Paginator
from django.views.generic import View, TemplateView, ListView

def test(request):
    print("request",request.POST)
    return HttpResponse("ok")

#解释说明：
"""
TemplateView自带的有一个GET请求的方法，返回的网页就是template_name = "user/userlist.html"，网页里面的传的数据内容可以通过重写get_context_data这个方法来获取，django自己写分页的话是利用列表的切片，类似于mysql的limit和offset，这里是引用自带的分页模块
"""
class CarView(TemplateView):
    template_name = "car/car_index.html"
    def get_context_data(self, **kwargs):
        #这个方法就可以将变量传到模板里
        context = super(CarView, self).get_context_data(**kwargs)
        try:
            page = int(self.request.GET.get("page","1")) #这里做了异常处理，如果page是字符，就会变成下面的page=1
        except:
            page = 1
        paginator = Paginator(Car.objects.all(),10)
        page_obj = paginator.page(page) #这个page_obj是为了和自带的方法保持一致
        context["object_list"] = page_obj.object_list # page_obj.object_list是要获得的
        context["page_obj"] = page_obj # page_obj 也是要获得的
        return context



def car_detail(request, year, month, day, name):
    car = get_object_or_404(Car,slug=name,\
                            date__year=year,\
                            date__month=month,\
                            date__day=day)
    content = {'car':car}
    return render(request,'car/car_detail.html',content)

from django.views.decorators.csrf import csrf_exempt
@csrf_exempt
def car_detail_ajax(request):
    if request.method == "POST":
        print("post")
        money = float(request.POST.get("money",0).strip())
        real_income = float(request.POST.get("real_income",0).strip())
        warning = '''
        <div class="alert alert-warning alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <strong>警告!</strong> <strong>实际金额低</strong>于应有收入，请核对看是否有问题.
</div>
        '''
        well = '''
        <div class="alert alert-success alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <strong>警告!</strong> <strong>实际金额高</strong>于应有收入，请核对看是否有问题.
</div>
        '''
        normal = '''
        <div class="alert alert-info alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <strong>正确!</strong> 实际金额等于应有收入，账单没什么问题.
</div>
        '''
        if money < real_income:
            return HttpResponse(warning)
        elif money > real_income:
            return HttpResponse(well)
        else:
            return HttpResponse(normal)
    print("get")
    return render(request,'car/car_detail.html')

#
# def car_create(request):
#     if request.method == "POST":
#         form = CarForm(request.POST,initial={"name":""})
#         print("POST")
#         if form.is_valid():
#             cd = form.cleaned_data
#             name = cd.get("name","")
#             driver = cd.get("driver","")
#             d = get_object_or_404(Driver,name__contains =driver)
#             saler = cd.get("saler","")
#             s = get_object_or_404(Saler, name__contains=saler)
#             people_30 = int(cd.get("people_30",0))
#             people_40 = int(cd.get("people_40",0))
#             food = cd.get("food",0)
#             things = cd.get("things",0)
#             oil = int(cd.get("oil",0))
#             total_income = int(people_40)*40+int(people_30)*30+int(things)
#             real_income = int(people_40)*40+int(people_30)*30+int(things)-int(food)
#             total_people = int(people_30)+int(people_40)
#             car = Car(name=name,total_income=total_income,oil=oil,total_people=total_people,\
#                       real_income=real_income,saler=s,driver=d,people_30=people_30,\
#                       people_40=people_40,food=food,things=things)
#             car.save()
#             print(cd)
#             return HttpResponseRedirect(reverse('car:car_index'))
#     else:
#         form = CarForm(initial={"name":""})
#     return render(request, "car/run_create.html",{'form':form})

# ajax创建车辆每日运行信息
def car_create_ajax(request):
    form = CarForm(request.POST)
    if form.is_valid():
        print("POST")
        cd = form.cleaned_data
        name = cd.get("name","")
        driver = cd.get("driver","")
        d = get_object_or_404(Driver,name__contains =driver)
        saler = cd.get("saler","")
        s = get_object_or_404(Saler, name__contains=saler)
        people_30 = int(cd.get("people_30",0))
        people_40 = int(cd.get("people_40",0))
        food = cd.get("food",0)
        things = cd.get("things",0)
        oil = int(cd.get("oil",0))
        total_income = int(people_40)*40+int(people_30)*30+int(things)
        real_income = int(people_40)*40+int(people_30)*30+int(things)-int(food)
        total_people = int(people_30)+int(people_40)
        car = Car(name=name,total_income=total_income,oil=oil,total_people=total_people,\
                  real_income=real_income,saler=s,driver=d,people_30=people_30,\
                  people_40=people_40,food=food,things=things)
        car.save()
        return JsonResponse({"status":200,"result":""})
    else:
        return JsonResponse({"status":400,'result':"",'errors':json.loads(form.errors.as_json())})

# 使用DataTable插件获取车辆信息
def get_car_info_ajax(request):
    cars = Car.objects.all()
    cars = [ car.as_dict() for car in cars]
    return JsonResponse({"data":cars})

#通过ajax获取每年的运营数据
def ajax_by_year(request):
    year = request.GET.get("year","2017")
    year_data = get_list_or_404(Car,date__year=year) #某一年的所有车辆数据
    dict_month = {}#该年的每个月的车辆的数据，月份为key，数据为value
    for i in year_data:
        # dict_month[i.date.month] = dict_month.get(i.date.month,[])+[(i.total_income,i.oil)]
        if i.date.month in dict_month:
            dict_month.get(i.date.month).append(((i.name,i.total_income,i.oil)))
        else:
            dict_month.setdefault(i.date.month,[(i.name,i.total_income,i.oil)])
    print(dict_month)
    dict_car ={}
    for m in dict_month:
        dict_car[m] ={}
        print('m','-->',m)
        for c in dict_month[m]:
            print('c','-->',c)
            if c[0] in dict_car[m]:
                print(dict_car[m],"-->",c)
                dict_car[m][c[0]] = (dict_car[m][c[0]][0]+c[1],dict_car[m][c[0]][1]+c[2])
            else:
                dict_car[m][c[0]] = (c[1],c[2])
    print('sum','-->',dict_car)
    return JsonResponse(dict_car)


from django.db.models import Q

class CarSearchView(TemplateView):
    template_name = "car/car_search.html"

    def get_context_data(self, **kwargs):
        #这个方法就可以将变量传到模板里
        context = super(CarSearchView, self).get_context_data(**kwargs)
        try:
            page = int(self.request.GET.get("page","1")) #这里做了异常处理，如果page是字符，就会变成下面的page=1
        except:
            page = 1
        keywords = self.request.GET.get("search", "")
        search_all = get_list_or_404(Car, Q(name__contains=keywords) | Q(driver__name__contains=keywords)|Q(saler__name__contains=keywords))
        print(search_all)
        paginator = Paginator(search_all,1)
        page_obj = paginator.page(page) #这个page_obj是为了和自带的方法保持一致
        context["object_list"] = page_obj.object_list # page_obj.object_list是要获得的
        context["page_obj"] = page_obj # page_obj 也是要获得的
        context['keywords'] = keywords
        return context

def static_car(request):
    if request.method == "POST":
        form = DateForm(request.POST, initial={"date":datetime.today()})
        if form.is_valid():
            cd = form.cleaned_data
            date_str = request.POST.get('date',datetime.today())
            print("date",date_str)
            date = datetime.strptime(date_str,'%Y-%m-%d')
            year = date.year
            month = date.month
            month_all = get_list_or_404(Car, date__year=year, date__month=month)
            print(month_all)
            return HttpResponseRedirect(reverse('car:static_car_month', args=(year,month)))
    else:
        form = DateForm()
    return render(request,"car/static_car.html",{"form":form})

def static_car_month(request,year,month):
    month_all = get_list_or_404(Car, date__year=year, date__month=month)
    try:
        page = int(request.GET.get("page", "1"))  # 这里做了异常处理，如果page是字符，就会变成下面的page=1
    except:
        page = 1
    paginator = Paginator(month_all, 3)
    page_obj = paginator.page(page)  # 这个page_obj是为了和自带的方法保持一致
    context = {}
    context["object_list"] = page_obj.object_list  # page_obj.object_list是要获得的
    context["page_obj"] = page_obj  # page_obj 也是要获得的
    return render(request, 'car/static_car_month.html', context)

#按年分
def car_by_year(request):
    year_all = Car.objects.all()
    years = list(set([i.date.year for i in year_all]))

    try:
        page = int(request.GET.get("page", "1"))  # 这里做了异常处理，如果page是字符，就会变成下面的page=1
    except:
        page = 1
    print(years)
    paginator = Paginator(years, 3)
    page_obj = paginator.page(page)  # 这个page_obj是为了和自带的方法保持一致
    context = {}
    context["object_list"] = page_obj.object_list  # page_obj.object_list是要获得的
    context["page_obj"] = page_obj  # page_obj 也是要获得的
    return render(request, 'car/car_by_year.html', context)

def car_by_year_detail(request,year):

car/templates/carbase.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>{% block title %}车辆管理系统{% endblock %}</title>
        <link rel="stylesheet" type="text/css" href="https://cdn.bootcss.com/bootstrap/3.3.6/css/bootstrap.min.css" />
        <link rel="stylesheet" type="text/css" href="http://cdn.bootcss.com/font-awesome/4.6.2/css/font-awesome.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'DataTables-1.10.15/media/css/dataTables.bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'DataTables-1.10.15/media/css/jquery.dataTables.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'sweetalert-master/dist/sweetalert.css' %}">
        <script type="text/javascript" src="/static/echarts.min.js"></script>
        {% block links %}{% endblock %}
        <style type="text/css">
            body {
                padding-top: 70px;
            }
            div.nav-slider{
                position:fixed;
                top:50px;
                bottom:0px;
                overflow-y: auto;
                background-color: #eee;
                padding-top: 20px;
            }
        </style>
    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
          <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">车辆管理系统</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
              <form class="navbar-form navbar-left" action="{% url 'car:car_search' %}" method="GET">
                <div class="form-group">
                  <input type="text" name='search' style="width:350px" class="form-control" placeholder="请输入车名或司机姓名或售票员姓名查找信息">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
              </form>
              <ul class="nav navbar-nav navbar-right">
                  <li><p class="navbar-text navbar-right">  欢迎 <a href="/account/">{{ request.user.username }}</a>, </p></li>
                <li><a href="/account/logout/" class="btn" role="button"> 退出登陆</a></li>
              </ul>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>
        <div class="container-fluid">
            <div class="col-md-2 nav-slider">
                <ul class="nav nav-pills nav-stacked">
                  <li role="presentation" {% block nav_car %}{% endblock %}><a href="{% url 'car:car_index' %}">车辆运营信息</a></li>
                  <li role="presentation" {% block nav_driver %}{% endblock %}><a href="{% url 'car:driver' %}">司机信息</a></li>
                  <li role="presentation" {% block nav_driversalary %}{% endblock %}><a href="{% url 'car:driver_salary_list' %}">司机薪资信息</a></li>
                  <li role="presentation" {% block nav_saler %}{% endblock %}><a href="{% url 'car:saler' %}">售票员信息</a></li>
                  <li role="presentation" {% block nav_salersalary %}{% endblock %}><a href="{% url 'car:saler_salary_list' %}">售票员薪资信息</a></li>
                  <li role="presentation" {% block nav_year %}{% endblock %}><a href="{% url 'car:car_by_year' %}">车辆每年运行信息</a></li>
                  <li role="presentation" {% block nav_month %}{% endblock %}><a href="{% url 'car:car_by_month' %}">车辆每月运行信息</a></li>
                  <li role="presentation" {% block nav_day %}{% endblock %}><a href="{% url 'car:car_by_day' %}">车辆每日运行信息</a></li>
                </ul>
            </div>
            <div class="col-md-10 col-md-offset-2">
                <!--正文开始-->
                {% block content %}
                {% endblock %}
                <!--正文结束-->
            </div>
        </div>

        <script type="text/javascript" src="https://cdn.bootcss.com/jquery/2.2.4/jquery.min.js" ></script>
        <script type="text/javascript" src="https://cdn.bootcss.com/bootstrap/3.3.6/js/bootstrap.min.js" ></script>
        <script type="text/javascript" src="{% static 'sweetalert-master/dist/sweetalert.min.js' %}" ></script>
        <script type="text/javascript" src="{% static 'DataTables-1.10.15/media/js/jquery.dataTables.min.js' %}" ></script>
        <script type="text/javascript" src="{% static 'DataTables-1.10.15/media/js/dataTables.bootstrap.min.js' %}" ></script>
    {% block script %}{% endblock %}
    </body>
</html>

car/templates/pagination.html
<nav aria-label="Page navigation">
  <ul class="pagination">
        {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
        {% endif %}
      {% for num in page_obj.paginator.page_range %}
          {% if page_obj.number == num %}
              <li class="active"><a href="#">{{ num }}<span class="sr-only">(current)</span></a></li>
          {% else %}
              <li><a href="?page={{ num }}">{{ num }}</a></li>
          {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
          <li>
            <a href="?page={{ page_obj.next_page_number }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span></a></li>
      {% endif %}
  </ul>
</nav>